# Generated by Django 5.1.6 on 2025-02-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Название города', max_length=100, unique=True)),
                ('air_temperature', models.FloatField(blank=True, help_text='Температура воздуха в градусах Цельсия', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Влажность в процентах', null=True)),
                ('visibility', models.FloatField(blank=True, help_text='Видимость в километрах', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Время последнего обновления данных')),
            ],
        ),
    ]
